delete windos-curses because github can't dowload
ERROR: Could not find a version that satisfies the requirement windows-curses==2.3.1 (from versions: none)